version: '3'
services:
  kottans_pizza:
    image: lempiy/kottans_pizza_api:v.0.2.0
    environment:
      - PORT=8080
    network_mode: "host"
    ports:
      - "8080:8080"
    container_name: kottans_pizza_service

  nginx:
    image: lempiy/nginx-certbox:v1.1
    network_mode: "host"
    environment:
      - DOMAIN=pizza-tele.ga
      - EMAIL=lempiyada@gmail.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/webrootauth:/etc/letsencrypt/webrootauth
    container_name: nginx_proxy

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    container_name: redis_pizza
